---
title: "Ensemble Deconvolution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, warning = F, message = T, cache = T, fig.width = 7, fig.height = 7,
  comment = "#>"
)
```

The testdata includes two different reference dataset (Nowakowski and Darmanis), and ROS bulk data (n = 10).

```{r setup}
library(foreach)
library(tidyverse)
library(EnsDeconv)
data(testdata)
```



# Use two reference data, two deconvoluton methods, one normaliztaion, one transformation, one marker gene approach.

```{r}
params = get_params(data_type = "singlecell-rna", data_name = names(testdata$ref_list), n_markers = 50,Marker.Method = "t",TNormalization = "CPM",CNormalization = "CPM",dmeths = c("EPIC","CIBERSORT"))
#generate all possible combinations
#params = get_params(data_type = "singlecell-rna", data_name = names(testdata$ref_list))

res = EnsDeconv(count_bulk = as.matrix(testdata$count_bulk), ref_list = testdata$ref_list, ncore = 4, parallel_comp = T, params = params,trueMet = "ROS",outpath = "./tmp/")


pheatmap::pheatmap(res[["EnsDeconv"]][["ensemble_p"]],cluster_rows = F,cluster_cols = F)
```

